version: '3.4'

volumes:
  postgres: {}

services:
  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
      DJANGO_SETTINGS_MODULE: config.settings_docker
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    ports:
      - 8080:80

  postgres:
    image: postgres:alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
